# This workflow configures the user-statistician with all of
# the defaults, which is a light theme, nothing hidden, etc.
# It is configured on a daily schedule at 3am.

name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/all-defaults.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入内容
      pages: write     # 如果有 GitHub Pages
      id-token: write  # 如果有 OIDC
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      env:
        GITHUB_TOKEN: ${{secrets.GGITHUB_TOKEN}}
